config/routes.rb
CsvImporter::Application.routes.draw do

  resources :attachments, except: [:edit] do
    resources :mappings, only: [:new, :create, :destroy]
    resources :imports, only: [:new, :create, :destroy]
  end
  resources :mappings, only: [:index, :show, :destroy]
  resources :imports, only: [:index, :show, :destroy]

  match 'login' => 'sessions#create', via: :post, as: :login
  match 'login_success' => 'sessions#new', via: :get, as: :login_success

  root to:  'frontend#index'
end

app/models/attachment.rb
# encoding: utf-8

# Store uploaded files, temporary until the import is created
#
# If files need to present afterwards should implement persistent s3 storage!!

require 'csv'

class Attachment < ActiveRecord::Base
  FILE_DIR = Rails.root.join('tmp', 'attachments')

  include UserReference

  belongs_to :mapping
  has_many :imports, dependent: :destroy

  default_scope ->{order('attachments.id desc')}

  after_create :store_file
  after_destroy :delete_file

  validates :filename, :disk_filename, presence: true
  validates :quote_char, :encoding, presence: true
  validate :col_sep_presence

  #attr_accessible :col_sep, :quote_char, :uploaded_data, :encoding, :mapping_id
  attr_reader :error_rows, :parse_error

  def col_sep=(original_value)
    self.send(:write_attribute, :col_sep, original_value == "\\t" ? "\t" : original_value)
  end

  # Any upload file gets passed in as uploaded_data attribute
  # Here its beeing parsed into its bits and pieces so the other attributes can
  # be set (filesize / filename / ..)
  # Sets instance var @uploaded_file, which points to a temp file object and is
  # stored to its final destination after save

  def uploaded_data=(data)
    return if data.nil? #&& data.size > 0
    #set new values
    self.filename = data.original_filename.strip.gsub(/[^\w\d\.\-]+/, '_')
    self.disk_filename = Attachment.disk_filename(filename)
    #check for small files indicated by beeing a StringIO
    @uploaded_file = data
  end

  # full path with filename
  def full_filename
    File.join(path, self.disk_filename)
  end

  def rows(size = 0)
    parsed_data[0..(size - 1)]
  end

  private

  # When parsing data, we expect our file to be saved as valid utf-8
  # TODO rescue parser errors -> rows empty
  def parsed_data
    @parsed_data ||= begin
      CSV.read(full_filename, col_sep: col_sep, quote_char: quote_char, encoding: encoding)
    rescue => e #CSV::MalformedCSVError => er
      @parse_error = e.to_s
      rows = []
      #one more attempt. If BOM is present in the file.
      begin
        f = File.open(full_filename, "rb:bom|utf-8")
        rows = CSV.parse(f.read.force_encoding("ISO-8859-1"))
      ensure
        return rows
      end
    end
  end

  # store the uploaded tempfile.
  def store_file
    # TODO
    # - kick BOM if present
    # - convert to UTF-8 if a different encoding is given
    # - we should check double encoding because the tempfile is always read as utf8

    # writes the file binary/raw without taking encodings into account.
    # If we want to convert incoming files this should be done before
    File.open(full_filename, 'wb') do |f| #w:UTF-8
      f.write @uploaded_file.read
    end
  end

  def delete_file
    File.delete(full_filename) rescue true #catch Errno::ENOENT exception for deleted files
  end

  def path
    FileUtils.mkdir_p(FILE_DIR) unless File.directory?(FILE_DIR)
    FILE_DIR
  end

  # Returns an ASCII or hashed filename prefixed with the current timestamp
  def self.disk_filename(filename)
    filename = filename.strip.gsub(/[^\w\d\.\-]+/, '_')
    #%L milliseconds 000-999
    df = DateTime.now.strftime("%y%m%d%H%M%S%L") + "_"
    if filename =~ %r{^[a-zA-Z0-9_\.\-]*$}
      df << filename
    else
      df << Digest::MD5.hexdigest(filename)
      # keep the extension if any
      df << $1 if filename =~ %r{(\.[a-zA-Z0-9]+)$}
    end
    df
  end

  def col_sep_presence
    (self.col_sep.present? || self.col_sep == "\t" ) || self.errors.add(:col_sep, :must_be_present)
  end
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  load_and_authorize_resource

  def new
    @attachment = Attachment.new(col_sep: ',', quote_char: '"', encoding: 'utf-8')
  end

  # TODO:
  # - check for headers if none use first data row
  # - hide headers/fields which are potentially empty
  # - find or construct a row with all data set, so we can show examples
  def create
    @attachment = Attachment.new(uploaded_data: params[:file], col_sep: params[:col_sep], quote_char: params[:quote_char], encoding: params[:encoding])
    @attachment.user = current_user
    @attachment.save!
    # TODO rescue parser errors -> rows empty
    rows = @attachment.rows(4)
    render json: {errors: @attachment.parse_error, id: @attachment.id, rows: rows}, status: :ok
  end

  def update
    if @attachment.update_attributes(attachment_params)
      respond_to do |format|
        format.html { redirect_to (@attachment.mapping.blank? ? new_attachment_mapping_url(@attachment) : new_attachment_import_url(@attachment))
          }
        format.js { render json: {rows: @attachment.rows(4)}, status: :ok }
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.js { render json: {rows: {}}, status: :ok }
      end
    end
  end

  def destroy
    @attachment.destroy
    redirect_to attachments_path
  end

  private

  def attachment_params
    params.require(:attachment).permit(:col_sep, :quote_char, :uploaded_data, :encoding, :mapping_id)
  end
end

app/views/attachments/index.haml
.header
  .head2
    .title
      = Attachment.model_name.human(count: 5)
      %small= @attachments.size
#side
  %a.btn.btn-danger{href: new_attachment_path, title: t(:'attachments.new.page_title')} 
    = t(:'link.new_import')

#content
  %table.table
    %thead
      %tr
        %th.check-column
          %input{id: "id", name: "id", type: "checkbox", value: 1}
        %th= Attachment.model_name.human(count: 1)
        %th= Mapping.model_name.human(count: 1)
        %th= Import.model_name.human(count: 1)
    %tbody
      - @attachments.each do |attachment|
        %tr
          %td.check-column
            %input{:type=>"checkbox", :name=>"ids[]", :value=>"#{attachment.id}"}
          %td
            = link_to(attachment.filename, attachment)
            = link_to(icon('trash-o'), attachment, data: {confirm: t('attachments.delete_confirm'), method: :delete})
            .created= l attachment.created_at
          %td
            - if attachment.mapping
              = link_to(attachment.mapping.title, attachment.mapping)
              = link_to(icon('trash-o'), [attachment, attachment.mapping], data: {confirm: t('mappings.delete_confirm'), method: :delete})
              .created= l attachment.mapping.created_at
            - else
              = link_to(t('mappings.new'), new_attachment_mapping_path(attachment))
          %td
            - if attachment.imports.any?
              - attachment.imports.each do |import|
                = link_to(import.title, import)
                = link_to(icon('trash-o'), [attachment, import], data: {confirm: t('imports.delete_confirm'), method: :delete})
                .created= l import.created_at
            - elsif attachment.mapping
              = link_to(t('imports.new'), new_attachment_import_path(attachment))

app/views/attachments/index.html.haml
%h2
  = Attachment.model_name.human(count: 5)
  %small= @attachments.size

%p= link_to t(:'attachments.new'), new_attachment_path

%table.attachments
  %thead
    %tr
      %th= Attachment.model_name.human(count: 1)
      %th= Mapping.model_name.human(count: 1)
      %th= Import.model_name.human(count: 1)
      %th
  %tbody
    - @attachments.each do |attachment|
      %tr
        %td
          = link_to(attachment.filename, attachment)
          .created= attachment.created_at
        %td
          - if attachment.mapping
            = link_to(attachment.mapping.title, attachment.mapping)
            .created= attachment.mapping.created_at
          - else
            = link_to(t('mappings.new'), new_attachment_mapping_path(attachment))
        %td
          - if attachment.imports.any?
            - attachment.imports.each do |import|
              = link_to(import.title, import)
              .created= import.created_at
          - elsif attachment.mapping
            = link_to(t('imports.new'), new_attachment_import_path(attachment))
        %td
          = link_to(image_tag('destroy.png'), attachment, :confirm => t('attachments.delete_confirm'), :method => :delete)

app/views/attachments/new.haml
.head2
  .title
    = t('link.step', step: 1, total: 3)
    = t('.page_title')

- if @attachment.errors.any?
  .alert-message.block-message.error
    %ul
      - @attachment.errors.full_messages.each do |i|
        %li=i

#side
  = form_for @attachment, method: 'patch' do |f|
    .side-list
      .side-list-item
        #button-locale
          = t('attachments.new.upload_button')
        - if @attachment.new_record?
          .clearfix
            .input
              #file-upload
                %noscript
                  %p=t('.enable_javascript')
      .side-list-item
        .clearfix
          = label_tag :col_sep, "#{Attachment.human_attribute_name(:col_sep)} <span class='required'> *</span>".html_safe
          .input
            = f.text_field :col_sep, class: 'minimi'
            %span.help-inline= t('.can_use_tab_character_html')
      .side-list-item
        .clearfix
          = label_tag :quote_char, "#{Attachment.human_attribute_name(:quote_char)} <span class='required'> *</span>".html_safe
          .input
            = f.text_field :quote_char, class: 'minimi'
      .side-list-item
        .clearfix
          = label_tag :encoding, "#{Attachment.human_attribute_name(:encoding)} <span class='required'> *</span>".html_safe
          .input
            = f.select :encoding, Encoding.name_list.sort_by{|word| word.downcase}, selected: 'UTF-8', class: 'input-mini'
            %span.info=t('.only_for_advanced_users')
      .side-list-item
        .actions
          = f.submit t('attachments.proceed_to_mapping'), class: "btn btn-primary btn-large", id: "continue-button", style: "display:none"
          = link_to t('link.back'), attachments_path, class: "btn secondary"

#content
  #invalid-csv-error.alert-message.block-message.error{style: 'display: none'}
  #csv-table.clearfix{style: ("display: none" if @attachment.new_record?)}
    %h2=t('.preview')
    %p=t('.preview_info')
    = link_to(image_tag("refresh.png", size: "16x16") + "Reload", "#", id: "csv-refresh")

app/views/attachments/new.html.haml
%h2
  = t('link.step', count: 1, total: 3)
  = t('attachments.new')

- if @attachment.errors.any?
  .alert-message.block-message.error
    %ul
      - @attachment.errors.full_messages.each do |i|
        %li=i

= form_for @attachment, method: 'put' do |f|
  .clearfix
    = label_tag :col_sep, "#{Attachment.human_attribute_name(:col_sep)} <span class='required'> *</span>".html_safe
    .input
      = f.text_field :col_sep, class: 'minimi'
  .clearfix
    = label_tag :quote_char, "#{Attachment.human_attribute_name(:quote_charp)} <span class='required'> *</span>".html_safe 
    .input
      = f.text_field :quote_char, class: 'minimi'
  .clearfix
    = label_tag :encoding, "#{Attachment.human_attribute_name(:encoding)} <span class='required'> *</span>".html_safe 
    .input
      = f.text_field :encoding
  - if @attachment.new_record?
    .clearfix
      %label=t(:'attachments.upload')
      .input
        #file-upload
          %noscript
            %p Please enable JavaScript to use file uploader
  #csv-table.clearfix{style: ("display: none" if @attachment.new_record?)}
    = link_to(image_tag("refresh.png", size: "16x16") + "Reload", "#", id: "csv-refresh")

  .actions
    = f.submit t('attachments.proceed_to_mapping'), class: "btn primary large"
    = link_to t('link.back_to_list'), attachments_path, class: "btn secondary"

app/views/attachments/show.haml
%h1
  = Attachment.model_name.human(count: 1)
  = @attachment.filename
%table
  - @attachment.rows.each do |row|
    %tr
      - row.each do |item|
        %td= item
.actions
  - unless @attachment.mapping.present?
    = link_to t('attachments.proceed_to_mapping'), new_attachment_mapping_path(@attachment), class: "btn primary large"
  = link_to t('link.back_to_list'), attachments_path, class: "btn secondary"

app/views/attachments/show.html.haml
%h1
  = Attachment.model_name.human(count: 1)
  = @attachment.filename
%table
  - @attachment.rows.each do |row|
    %tr
      - row.each do |item|
        %td= item
.actions
  - unless @attachment.mapping.present?
    = link_to t('attachments.proceed_to_mapping'), new_attachment_mapping_path(@attachment), class: "btn primary large"
  = link_to t('link.back_to_list'), attachments_path, class: "btn secondary"