config/routes.rb
CsvImporter::Application.routes.draw do

  resources :attachments, except: [:edit] do
    resources :mappings, only: [:new, :create, :destroy]
    resources :imports, only: [:new, :create, :destroy]
  end
  resources :mappings, only: [:index, :show, :destroy]
  resources :imports, only: [:index, :show, :destroy]

  match 'login' => 'sessions#create', via: :post, as: :login
  match 'login_success' => 'sessions#new', via: :get, as: :login_success

  root to:  'frontend#index'
end

app/views/layouts/application.haml
!!! Strict
%html{ 'xmlns' => 'http://www.w3.org/1999/xhtml', 'xml:lang' => I18n.locale, 'lang' =>  I18n.locale }
  %head
    %title= 'SalesKing CSV Importer'
    = stylesheet_link_tag    'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    = yield :head
  %body
    %header#header.clearfix
      .head1
        %nav.navbar.clearfix(role="navigation")
          %ul.nav.navbar-nav
            %li= link_to t('.attachments'), attachments_path, class: ('current' if request.fullpath =~ /attachments/)
            %li= link_to t('.mappings'),    mappings_path,    class: ('current' if request.fullpath =~ /mappings/)
            %li= link_to t('.imports'),     imports_path,     class: ('current' if request.fullpath =~ /imports/)
    %br
    %br

    = yield

app/views/layouts/frontend.haml
!!! Strict
%html{ "xmlns" => "http://www.w3.org/1999/xhtml", "xml:lang" => I18n.locale, "lang" =>  I18n.locale }
  %head
    %title= 'SalesKing CSV Importer'
    = stylesheet_link_tag    "application"
    = stylesheet_link_tag    "frontend"
  %body
    .topbar
      .fill
        .container
          %a(class="brand" href="#")CSV Importer
          %ul.nav
            %li.active
              %a(href="https://salesking.eu")Login to SalesKing

    .container
      = yield
      %footer
        %p &copy; 2011 Georg Leciejewski - SalesKing GmbH